In [2]:
import numpy as np
s = 20
X_train = []
for i in range(1,6):
    for j in range(1,6):
        X_train.append([i,j])

X_train = np.array(X_train)
y_train = np.array([[i*i, j*j] for i,j in X_train])

In [3]:
X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1],1))
y_train = np.reshape(y_train, (y_train.shape[0],y_train.shape[1],1))
y_train[s:].shape

(5, 2, 1)

In [4]:
W = np.random.randn(2,2)
W

array([[ 0.71524838, -1.31803376],
       [-0.03997422,  0.87079455]])

In [5]:

print(X_train[s:].shape)
X_in = np.dot(W,X_train[s:])
print(X_in)

(5, 2, 1)
[[[ 2.25820812]
  [ 0.94017436]
  [-0.3778594 ]
  [-1.69589317]
  [-3.01392693]]

 [[ 0.67092346]
  [ 1.54171801]
  [ 2.41251257]
  [ 3.28330712]
  [ 4.15410168]]]


In [6]:
from Layers import Layer
L1 = Layer(2,2)
# np.dot(L1.W, X_train[s:])
X_in = L1._forward(X_in = X_train[s:])
# np.rehape(ans1, y_train[s:].shape) 

In [7]:
X_in.shape

(5, 2, 1)

In [8]:
from Layers import Activation
# X_in = np.reshape(X_in,y_train[s:].shape)
L = Activation('sigmoid')
ans = L._forward(X_in)
print(ans)

[[[0.91501828]
  [0.99634429]]

 [[0.85482612]
  [0.99334957]]

 [[0.76304087]
  [0.98793134]]

 [[0.63781241]
  [0.97819568]]

 [[0.49058611]
  [0.96091703]]]


In [9]:
k = np.array([L1.W.dot(i) for i in X_train[s:]])
# print(k)
print(L1.B)
print(k+L1.B)

[[-1.59748566]
 [ 0.39772612]]
[[[ 2.37650786]
  [ 5.60780182]]

 [[ 1.77296589]
  [ 5.00640168]]

 [[ 1.16942392]
  [ 4.40500155]]

 [[ 0.56588194]
  [ 3.80360141]]

 [[-0.03766003]
  [ 3.20220127]]]


In [10]:
print(y_train[s:].shape)
# ans = np.reshape(ans,y_train[s:].shape)
print(ans-y_train[s:])

(5, 2, 1)
[[[-2.40849817e+01]
  [-3.65571263e-03]]

 [[-2.41451739e+01]
  [-3.00665043e+00]]

 [[-2.42369591e+01]
  [-8.01206866e+00]]

 [[-2.43621876e+01]
  [-1.50218043e+01]]

 [[-2.45094139e+01]
  [-2.40390830e+01]]]


In [11]:
from Errors import *
er = mse_prime(ans,y_train[s:])
print(er)

[[[-4.81699634e+00]
  [-7.31142527e-04]]

 [[-4.82903478e+00]
  [-6.01330085e-01]]

 [[-4.84739183e+00]
  [-1.60241373e+00]]

 [[-4.87243752e+00]
  [-3.00436086e+00]]

 [[-4.90188278e+00]
  [-4.80781659e+00]]]


In [12]:
b_o = L._backward(er)

In [13]:
t = L1._backward(er)
t
# t.sum(axis = 0)

array([[[ -4.41084415],
        [  2.90769919]],

       [[ -5.11993867],
        [  3.27616517]],

       [[ -6.30029936],
        [  3.88929626]],

       [[ -7.95270525],
        [  4.74754358]],

       [[-10.07581047],
        [  5.84991356]]])

In [14]:
er.sum(axis = 0)

array([[-24.26774324],
       [-10.01665242]])

In [25]:
b = np.random.randint(0,10,(1,4))
c = np.random.randint(0,10,(3,4))
print(b)
print(c)

[[6 2 1 5]]
[[5 7 6 2]
 [0 6 2 5]
 [5 6 1 3]]


In [26]:
c+b

array([[11,  9,  7,  7],
       [ 6,  8,  3, 10],
       [11,  8,  2,  8]])

In [28]:
b - c.sum(axis = 0)

array([[ -4, -17,  -8,  -5]])

In [1]:
import numpy as np
y = np.random.randn(4,3,3)
d = np.random.randn(4,3,3)
z = np.random.randint(10,20,(4,2,2))
# print(y)
# print(z)

In [2]:
from scipy import signal
ans = np.zeros_like(z[0])
for a,b in zip(y,z):
    ans+=signal.correlate2d(a,b, mode = 'valid')
print(ans)

from Layers import Convolutional

L = Convolutional(y.shape, (2,2),1)
k = L._forward(y)
c = L._backward(k)

[[1015 1034]
 [1172 1275]]


In [3]:
print(c)

[[[ 1.13437354e+00  9.76362482e+00  7.09034738e+00]
  [ 3.25921943e+01  4.18503118e+01  7.45049189e+00]
  [ 3.58458968e+01  1.56395711e+01  1.69748660e+00]]

 [[ 1.94278064e+00  1.44333757e+01 -5.71976657e+00]
  [ 5.39942457e+01 -6.35090232e+00 -5.18001689e+00]
  [ 1.10565086e+01 -1.57413938e+00 -7.74218778e-01]]

 [[-7.53676597e-01 -5.23534557e+00  5.05961648e+00]
  [-2.25269100e+01  2.26138423e-01  4.53194947e+00]
  [-4.78899602e+01 -6.51518839e+00  6.48869506e-01]]

 [[ 3.08384943e-01  2.84538732e+00  3.41933321e+00]
  [ 8.94690082e+00  1.69325465e+01  3.48191186e-02]
  [ 1.21325794e+01 -6.07711087e+00 -1.73188411e+00]]]


In [14]:
from Errors import Error_functions
from Layers import Activation

L = Activation('sigmoid')
y = L._forward(y)
d = L._forward(d)

In [15]:
def binary_entropy_loss(calc, actual):
    return 1/calc.shape[0]*((actual * np.log(calc)) + ((1-actual)*np.log(1-calc)))

binary_entropy_loss(y,d)

array([[[-0.67061343, -0.27349848, -0.29286025],
        [-0.16777855, -0.17875947, -0.23185891],
        [-0.18614487, -0.14605692, -0.12369256]],

       [[-0.32065155, -0.36131718, -0.15575924],
        [-0.18685194, -0.19151604, -0.17346657],
        [-0.23700734, -0.22333815, -0.15931438]],

       [[-0.17790478, -0.16337983, -0.17114075],
        [-0.17134497, -0.2994219 , -0.20380425],
        [-0.43997289, -0.17500802, -0.14283856]],

       [[-0.0909321 , -0.23755954, -0.17717851],
        [-0.22266375, -0.1523317 , -0.17240857],
        [-0.2201784 , -0.21154052, -0.18422973]]])

In [3]:
from Regularisers import Regularisation

k = Regularisation.l2()
print(k(y))

[[[ 0.  0.  0.]
  [-0.  0. -0.]
  [-0. -0. -0.]]

 [[-0. -0.  0.]
  [-0.  0. -0.]
  [ 0.  0. -0.]]

 [[ 0.  0. -0.]
  [-0. -0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0. -0.]
  [-0.  0.  0.]
  [ 0.  0. -0.]]]
